import { ExchangeServer, CloudRegion } from "../types";

export const enhancedExchangeServers: ExchangeServer[] = [
  {
    id: "binance-tokyo-1",
    name: "Binance",
    location: { city: "Tokyo", country: "Japan", lat: 35.6762, lon: 139.6503 },
    cloudProvider: "AWS",
    region: "ap-northeast-1",
  },
  {
    id: "binance-ireland",
    name: "Binance",
    location: {
      city: "Dublin",
      country: "Ireland",
      lat: 53.3498,
      lon: -6.2603,
    },
    cloudProvider: "AWS",
    region: "eu-west-1",
  },
  {
    id: "binance-singapore",
    name: "Binance",
    location: {
      city: "Singapore",
      country: "Singapore",
      lat: 1.3521,
      lon: 103.8198,
    },
    cloudProvider: "AWS",
    region: "ap-southeast-1",
  },
  {
    id: "coinbase-us-east",
    name: "Coinbase",
    location: { city: "Virginia", country: "USA", lat: 37.4316, lon: -78.6569 },
    cloudProvider: "AWS",
    region: "us-east-1",
  },
  {
    id: "coinbase-us-west",
    name: "Coinbase",
    location: { city: "Oregon", country: "USA", lat: 43.8041, lon: -120.5542 },
    cloudProvider: "AWS",
    region: "us-west-2",
  },
  {
    id: "kraken-us-east",
    name: "Kraken",
    location: { city: "New York", country: "USA", lat: 40.7128, lon: -74.006 },
    cloudProvider: "AWS",
    region: "us-east-1",
  },
  {
    id: "kraken-frankfurt",
    name: "Kraken",
    location: {
      city: "Frankfurt",
      country: "Germany",
      lat: 50.1109,
      lon: 8.6821,
    },
    cloudProvider: "AWS",
    region: "eu-central-1",
  },
  {
    id: "okx-singapore",
    name: "OKX",
    location: {
      city: "Singapore",
      country: "Singapore",
      lat: 1.3521,
      lon: 103.8198,
    },
    cloudProvider: "AWS",
    region: "ap-southeast-1",
  },
  {
    id: "okx-tokyo",
    name: "OKX",
    location: { city: "Tokyo", country: "Japan", lat: 35.6762, lon: 139.6503 },
    cloudProvider: "AWS",
    region: "ap-northeast-1",
  },
  {
    id: "bybit-singapore",
    name: "Bybit",
    location: {
      city: "Singapore",
      country: "Singapore",
      lat: 1.3521,
      lon: 103.8198,
    },
    cloudProvider: "AWS",
    region: "ap-southeast-1",
  },
  {
    id: "bybit-tokyo",
    name: "Bybit",
    location: { city: "Tokyo", country: "Japan", lat: 35.6762, lon: 139.6503 },
    cloudProvider: "AWS",
    region: "ap-northeast-1",
  },
  {
    id: "deribit-amsterdam",
    name: "Deribit",
    location: {
      city: "Amsterdam",
      country: "Netherlands",
      lat: 52.3676,
      lon: 4.9041,
    },
    cloudProvider: "GCP",
    region: "europe-west4",
  },
  {
    id: "bitfinex-london",
    name: "Bitfinex",
    location: { city: "London", country: "UK", lat: 51.5074, lon: -0.1278 },
    cloudProvider: "Azure",
    region: "uksouth",
  },
  {
    id: "huobi-singapore",
    name: "Huobi",
    location: {
      city: "Singapore",
      country: "Singapore",
      lat: 1.3521,
      lon: 103.8198,
    },
    cloudProvider: "AWS",
    region: "ap-southeast-1",
  },
  {
    id: "huobi-seoul",
    name: "Huobi",
    location: {
      city: "Seoul",
      country: "South Korea",
      lat: 37.5665,
      lon: 126.978,
    },
    cloudProvider: "AWS",
    region: "ap-northeast-2",
  },
  {
    id: "kucoin-singapore",
    name: "KuCoin",
    location: {
      city: "Singapore",
      country: "Singapore",
      lat: 1.3521,
      lon: 103.8198,
    },
    cloudProvider: "AWS",
    region: "ap-southeast-1",
  },
  {
    id: "kucoin-sydney",
    name: "KuCoin",
    location: {
      city: "Sydney",
      country: "Australia",
      lat: -33.8688,
      lon: 151.2093,
    },
    cloudProvider: "GCP",
    region: "australia-southeast1",
  },
  {
    id: "gate-singapore",
    name: "Gate.io",
    location: {
      city: "Singapore",
      country: "Singapore",
      lat: 1.3521,
      lon: 103.8198,
    },
    cloudProvider: "AWS",
    region: "ap-southeast-1",
  },
  {
    id: "gate-seoul",
    name: "Gate.io",
    location: {
      city: "Seoul",
      country: "South Korea",
      lat: 37.5665,
      lon: 126.978,
    },
    cloudProvider: "Azure",
    region: "koreacentral",
  },
  {
    id: "mexc-singapore",
    name: "MEXC",
    location: {
      city: "Singapore",
      country: "Singapore",
      lat: 1.3521,
      lon: 103.8198,
    },
    cloudProvider: "AWS",
    region: "ap-southeast-1",
  },
  {
    id: "bitget-singapore",
    name: "Bitget",
    location: {
      city: "Singapore",
      country: "Singapore",
      lat: 1.3521,
      lon: 103.8198,
    },
    cloudProvider: "AWS",
    region: "ap-southeast-1",
  },
  {
    id: "crypto-singapore",
    name: "Crypto.com",
    location: {
      city: "Singapore",
      country: "Singapore",
      lat: 1.3521,
      lon: 103.8198,
    },
    cloudProvider: "AWS",
    region: "ap-southeast-1",
  },
  {
    id: "gemini-us-east",
    name: "Gemini",
    location: { city: "New York", country: "USA", lat: 40.7128, lon: -74.006 },
    cloudProvider: "AWS",
    region: "us-east-1",
  },
  {
    id: "bitstamp-luxembourg",
    name: "Bitstamp",
    location: {
      city: "Luxembourg",
      country: "Luxembourg",
      lat: 49.6116,
      lon: 6.1319,
    },
    cloudProvider: "AWS",
    region: "eu-west-1",
  },
];

export const enhancedCloudRegions: CloudRegion[] = [
  {
    id: "aws-us-east-1",
    provider: "AWS",
    name: "US East (Virginia)",
    code: "us-east-1",
    location: { lat: 37.4316, lon: -78.6569 },
    serverCount: 25,
  },
  {
    id: "aws-us-west-2",
    provider: "AWS",
    name: "US West (Oregon)",
    code: "us-west-2",
    location: { lat: 43.8041, lon: -120.5542 },
    serverCount: 18,
  },
  {
    id: "aws-eu-west-1",
    provider: "AWS",
    name: "Europe (Ireland)",
    code: "eu-west-1",
    location: { lat: 53.3498, lon: -6.2603 },
    serverCount: 22,
  },
  {
    id: "aws-eu-central-1",
    provider: "AWS",
    name: "Europe (Frankfurt)",
    code: "eu-central-1",
    location: { lat: 50.1109, lon: 8.6821 },
    serverCount: 20,
  },
  {
    id: "aws-ap-southeast-1",
    provider: "AWS",
    name: "Asia Pacific (Singapore)",
    code: "ap-southeast-1",
    location: { lat: 1.3521, lon: 103.8198 },
    serverCount: 30,
  },
  {
    id: "aws-ap-northeast-1",
    provider: "AWS",
    name: "Asia Pacific (Tokyo)",
    code: "ap-northeast-1",
    location: { lat: 35.6762, lon: 139.6503 },
    serverCount: 28,
  },
  {
    id: "aws-ap-northeast-2",
    provider: "AWS",
    name: "Asia Pacific (Seoul)",
    code: "ap-northeast-2",
    location: { lat: 37.5665, lon: 126.978 },
    serverCount: 15,
  },
  {
    id: "gcp-europe-west4",
    provider: "GCP",
    name: "Europe West (Netherlands)",
    code: "europe-west4",
    location: { lat: 52.3676, lon: 4.9041 },
    serverCount: 16,
  },
  {
    id: "gcp-australia-southeast1",
    provider: "GCP",
    name: "Australia (Sydney)",
    code: "australia-southeast1",
    location: { lat: -33.8688, lon: 151.2093 },
    serverCount: 12,
  },
  {
    id: "azure-uksouth",
    provider: "Azure",
    name: "UK South",
    code: "uksouth",
    location: { lat: 51.5074, lon: -0.1278 },
    serverCount: 14,
  },
  {
    id: "azure-koreacentral",
    provider: "Azure",
    name: "Korea Central",
    code: "koreacentral",
    location: { lat: 37.5665, lon: 126.978 },
    serverCount: 11,
  },
];
